### ISSUE TITLE
Way to sign in on restricted pages

### ISSUE THREAD

**Issue by Brekmister** [superhawk610/multicast#22]
So, I have a dilemma.

How the heck am I supposed to sign in to webpages such as this on the Chromecast?

![screenshot from 2017-10-15 17-30-43](https://user-images.githubusercontent.com/8389366/31590131-e618b684-b1d0-11e7-8ebd-70a5156e20a2.png)

Do I need a proxy that will do the kerberos sign in for me? or can we have a step recorder on the preview page on the channel? or Do I make a custom template that posts the credentials then fetches the page? Tell me, I would like to know.

**Side Note:** this is what I am trying to get to display on a TV/monitor

![screenshot from 2017-10-15 17-53-32](https://user-images.githubusercontent.com/8389366/31590195-d0afc408-b1d1-11e7-90ef-f7c4664b6e36.png)

**Comment by ocelotsloth** [comment]
My initial reaction is to suggest pulling the cookies from your logged in session, but it might take some tinkering to get working right.

It would have to use the same idea as this: https://stackoverflow.com/q/14573223

**Comment by ocelotsloth** [comment]
On second thought, and I've never used Fedora Cockpit, but this looks like what you want:

http://cockpit-project.org/guide/latest/embedding.html

>Cockpit components are HTML files contained in packages. These can be placed in an iframe or web browser window.

**Comment by Brekmister** [comment]
Still needs a cookie otherwise my request gets ignored.

**Comment by Brekmister** [comment]
Hmmmmm...
This looks interesting:
http://phantomjs.org/page-automation.html

**Comment by Brekmister** [comment]
Unfortunately then we will have to deal with expiring cookies.

I think an Reverse proxy would work for a private network.

**Comment by superhawk610** [comment]
Spoofing cookies is a pain in the ass, and incredibly specific to each webpage in question. I think PhantomJS may actually be the most straightforward solution to this, but its interface is a little confusing to newcomers and will require specific scripting for each page you need to access. I do agree that this would be a great feature (almost necessary for in-house monitoring applications like your own) but I think it falls outside the limitations of a Chromecast.

Some sort of step recorder capable of translating a user's actions while logging in to a PhantomJS login script would be incredible here, but that's definitely a full project on its own.

**Comment by koenvb** [comment]
This would be a really helpful feature! 
We have for example several PowerBI reports where you need to login
using your office  365 credentials. 
Are there any other workarounds for this?

**Comment by koenvb** [comment]
Would headless chrome help here in any way? https://developers.google.com/web/updates/2017/04/headless-chrome 
Would love to get this working with logins!

**Comment by superhawk610** [comment]
@koenvb Basic auth should already work with Multicast, you can just enter the URL as such:

```shell
http://username:password@host.extension/
```

I saw Chrome's headless project (Puppeteer](https://github.com/GoogleChrome/puppeteer) and thought it looked promising too - it would be relatively easy to implement scripted login using such a framework, but then what? We can establish a logged in session *inside a headless environment*, but that doesn't transfer at all to the Chromecast, we would have to write a wrapper for the headless environment to relay its page content to the Chromecast... There has to be a better way.

The issue is this: Chromecast is meant to function in one of two ways, either as a web browser with no external inputs, or as a video receiver where user content is encoded from the sender device into a video stream and then piped in - this mode allows input, but kills video quality and requires the sender device to remain turned on and connected, so isn't really an option. Because of this, I think spoofing cookies may be the only way to do it, in which case Puppeteer may actually be the solution, with the process looking something like:

- establish headless session via Puppeteer
- scrape the page for username/password inputs and request credentials OR log in using a series of scripted actions based on unique element identifiers (CSS selectors)
- grab all the cookies assigned and add them to any requests sent by the Multicast channel page for that specific channel

This would probably take a few iterations to do correctly. If nobody steps forward once to take this over, I'll start working on it after v3 is released.

**Comment by superhawk610** [comment]
Another approach is to interact with the login page directly via JS, which normally is blocked due to XSS concerns. However, we could proxy the iframe contents ourselves, strip problematic `X-Frame-Options` headers and add an `Access-Control-Allow-Origin` header that points to the Multicast hub page URL. Once that's done, it would be as simple as scripting the login process and inputting it via jQuery's `$('iframe').contents()` method. I think this is the way to proceed.

**Comment by superhawk610** [comment]
The complexity and deployment-specific issues inherent with a feature like this are together too much to allow it to be a core goal for the project. With v3.0 I'm trying to hone MultiCast to do a really good job at one thing, and this is too far outside of that core goal to justify the attention it would require to do correctly.
