### ISSUE TITLE
Have a configuration page at first launch and/or DB error

### ISSUE THREAD

**Issue by Brekmister** [superhawk610/multicast#24]
I apologize for adding to the stack of things that can be worked on but, In order to cleanly get issue #11 completed, I need to have the configuration and starting the service into the same command.

What I prefer to happen is to add a configuration page that pops up when you first access Multicast from a webpage. (Wordpress is an awesome example of this)

Also, have the page pop up again if multicast is having issues with the Database.

Apart from enabling the use of Docker, it's probably a more user-friendly option to have a webpage explaining what Multicast needs to know.

**Comment by superhawk610** [comment]
No I totally agree, that sort of interface would be great - my favorite log manager [PimpMyLog](https://github.com/potsky/PimpMyLog) also has a really great implementation.

I'm currently working on channel URL rotation, but I think this would be a great feature to add next, possibly along with implementing a persistent background daemon instead of having to use an external tool like PM2 to run for production use.

**Comment by potsky** [comment]
> my favorite log manager PimpMyLog also has a really great implementation

Hey thank you ;-)

**Comment by superhawk610** [comment]
This issue is being incorporated into the v3.0 release milestone.
