### ISSUE TITLE
Can this be used with chromecasts over public internet?

### ISSUE THREAD

**Issue by micschk** [superhawk610/multicast#29]
We have screens across multiple physical locations, (how) would it be possible to set up Multicast on a public server and control these screens? The screens would be in separate LANs, behind routers & possibly firewalls.

**Comment by Brekmister** [comment]
Sort of an idea: have mdns clients connect to a master server and that
connection goes through public internet?

**Comment by superhawk610** [comment]
@Brekmister that's exactly how I would configure it. In order to do this as logically as possible, I would:

1. extend Multicast's service to a full-fledged API
2. modify the existing interface to interact with the service via API calls, not directly
3. extend the existing interface to allow replicating calls to multiple endpoints, to mirror service across multiple locations
4. create a modified configuration tool that allowed for installing just the API/mDNS client, not the full interface, to create a server to act as an API endpoint

I do think this is a reasonable goal. I'll make a milestone for version 3.0.

**Comment by micschk** [comment]
Awesome @superhawk610 ! 

I'm new to mDNS/nodeJS, but quite seasoned in JS in general. 
Please do let me know if you could use any help.

**Comment by superhawk610** [comment]
@micschk I'll be adding the API schema to the milestone (#30),  you're more than welcome to take over building out the current program functions to an API, or changing the current functions to reference the API instead. We'll do work for this milestone on the `api` branch, you may want to watch #30 for progress updates and to participate in the discussion.

**Comment by superhawk610** [comment]
After some reflection, I think this is out of scope for this project. I've been putting off working on this due to the sheer scale of this goal, and I'd rather get out a really stable product that does one thing (local deployment) really well than a buggy product on a much larger scale.

If anyone else comes across this at a later date and would like to take up the lead, by all means go for it. Feel free to get in touch and I'll provide as much support as I can.
