### ISSUE TITLE
Clearing out Mongo

### ISSUE THREAD

**Issue by RobinBones** [superhawk610/multicast#58]
Some how I ended up with a chromecast registered with some missing information. When I view the /devices screen, I see an off line chromecast with no name. The URL is "/devices/undefined/edit". 

Is there a simple way I can flush MongoDB and start over configuring things? Maybe a message I can post to mongoDB or a URL I can request?

**Comment by superhawk610** [comment]
You should be able to drop Multicast's database in your Mongo instance and create a new one to get a clean slate. If your Mongo DB was named `multicast`, the following should take care of that:

```
mongo
use multicast
db.dropDatabase()
use multicast
```

Obviously be sure you want to do this since dropping a database will clear any existing data you have stored there. If you want to read more, check out Mongo's docs on the operation [here](https://docs.mongodb.com/manual/reference/method/db.dropDatabase/).

Make sure you stop your Multicast instance before performing this operation, then once you finish start it back up and you should be back at square 1.

On the other hand, you should be able to manually remove the faulty Chromecast entry from the `devices` collection, something like

```
mongo
use multicast
db.devices.find() // locate faulty record
db.devices.remove({ id: <faulty_record_id> )}
```

I'm going to go ahead and close this issue, but please feel free to post further info if the above solutions do not work. Thanks for using Multicast!

**Comment by RobinBones** [comment]
Thanks, I was able to find the bad record and remove it using the commands below.

```
mongo
use multicast
db.chromecasts.find() 
db.chromecasts.remove({_id:ObjectId("5cb5eb336a46d7e112400227"})
```
