### ISSUE TITLE
Chromecast ultra problem

### ISSUE THREAD

**Issue by thomasvjohansen** [superhawk610/multicast#68]
Im just setting up a Chromecast ultra. It's registered at Google Dev and multicast can see it and adopt it. Even preview channel on it works. But it's not sending anything the the Chromecast. Is there anything special about the 4k because when I tested it with a normal Chromecast V3 it worked fine.

**Comment by thomasvjohansen** [comment]
might be a selfconflicting problem.... logged in remote from home and could see I had messed up the network interface of my virtual server, so it had incorrect internet access. Will test it tomorrow to see if this fixed the problem.
Will close issue if it fixed it.

though strange the multicast server could see the chromecast as "registered" if it hadnt internet?

**Comment by thomasvjohansen** [comment]
i dont get it....

I can ping it, 
I can cast to it from my phone,
I can see it in multicast server,  
When I click preview I can see the channel preview,
but it wont send the channel to the chromecast.

any good ideas?

**Comment by LBegnaud** [comment]
is the channel defined via an IP or via a dns name? I've had difficulty getting greenscreen (the old version of this project) to work as the chromecast defaults to google dns. You can get it working via dns, but it's simpler to define channels via IP if it's a local webserver. Or are you having trouble getting multicast to takeover the chromecast altogether? might be an issue with the appid you registered being defined by a dns name that doesn't externally resolve (same issue, different layer).

**Comment by thomasvjohansen** [comment]
the channel is defined via ip. The firewall rules are those only for the server or are they for the router?

**Comment by superhawk610** [comment]
The firewall rules should be applied to the server running Multicast (so the Ubuntu VM in your case).

If it's working correctly at home and not at work, you're likely running into some issues with your work's network configuration - these are the hardest to diagnose and the worst to debug since they're so specific to your exact network setup.

If you're running Multicast from within a VM, maybe try playing around with other network modes? The Chromecast needs to be able to interface with your Multicast instance directly, and it may be blocked from doing so if the ports aren't correctly forwarding from your VM host to the VM itself.

**Comment by thomasvjohansen** [comment]
Thx for clarifying that it comunicates directly in the lan network with the client. Then I know where to tweak my office network.

**Comment by thomasvjohansen** [comment]
Finally got i sorted, sort of.....

Retried at home, and suddenly it didnt work.
Removed the mongodb, and reinstalled.
And removed the "application id" and readded it at google dev.

Reinstalled multicast, and reconfigured it.
Rebooted a few times
Rebooted after adding chromecasts, and then it worked again.

Back to my workplace and tried the same thing and after some struggle it worked too.

So it was not a firewall problem.
