### ISSUE TITLE
*URL* refused to connect.

### ISSUE THREAD

**Issue by mike-bond** [superhawk610/multicast#69]
I just installed/configured multicast, and I am trying to use private and public urls. 

When I do a preview, I get this at the top: 
Error! Frame loading blocked due to cross-origin prevention

And in the iFrame I get: 
*URL* refused to connect.

I have opened port 80, 443, 1900, and 5353. 

Thanks!

**Comment by metalcoat** [comment]
I used the fix here:
https://github.com/superhawk610/multicast/issues/65#issuecomment-536301883
Duplicate of #65

**Comment by mike-bond** [comment]
@metalcoat I'll look at that, but that is also 1/2 the issue, it can't connect to private or public urls.

**Comment by metalcoat** [comment]
What's not connecting? Is the screen white with that error at the top?

**Comment by mike-bond** [comment]
@metalcoat using a public video from youtube as an example (https://youtu.be/rS00xWnqwvI), I took a screen shot of me doing a preview:
![Screenshot from 2019-10-10 09-51-56](https://user-images.githubusercontent.com/56368675/66589638-cd3a5880-eb43-11e9-80d1-c40ec88963dd.png)

**Comment by metalcoat** [comment]
I'm not at my setup right now but did you embed it? https://www.youtube.com/embed/rS00xWnqwvI

**Comment by mike-bond** [comment]
@metalcoat that embed loads the URL, but does not play it. 
I also tried "https://www.youtube.com/embed/rS00xWnqwvI?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" and it didn't play it either. Also I get the refused to connect for both google slides, as well as other dashboards, which is the reason why I am looking at this solution.

**Comment by metalcoat** [comment]
https://www.youtube.com/embed/rS00xWnqwvI?autoplay=1&loop=1 is what you are probably looking for

**Comment by mike-bond** [comment]
@metalcoat So that works.
The more important problem is that I cannot get Google Slides to work with an embed url, nor can I get another dashboard to work with an embedded url. The documentation doesn't seem to cover what urls work best or not etc.

**Comment by metalcoat** [comment]
These issues are most likely not in relation to multicast but the urls you are using incorrectly.

That being said, I personally use google slides for my system, you'll need to use the following: 
https://docs.google.com/presentation/d/SlideUrlCodeHere/preview?rm=minimal&slide=id.slide_id_here

The rm=minimal removes the navigation bar which you probably want.  I could only get mine to work with the preview? switch
I hope that helps.

**Comment by mike-bond** [comment]
@metalcoat amazing! I was able to get the first slide to load. It doesn't seem to autoplay, but it looks like I can add additional URLs for the same channel for each of the slides and have it cycle through those.
I also need to do the fix from #65 

Lastly, do you you use JIRA dashboards? That's also one that my team would like to display.

**Comment by metalcoat** [comment]
We don't use Jira, is authentication required?

**Comment by superhawk610** [comment]
@metalcoat thanks so much for your help. When developing this project, I only used it in a small company setting to display pages on internal IPs so I don't have much experience getting 3rd party services to display correctly. With the next major version I'd like to include some documentation on common 3rd party use cases (such as YouTube videos and Google Slides); if you'd like to open a PR to add what you've shared in this thread to the readme or a new markdown document called `thirdparty.md`, that'd be super appreciated. Feel free to attribute yourself for that if you do.

@mike-bond I imagine JIRA dashboards are going to be a hassle since they will require authentication, which the current version of Multicast doesn't handle at all. I've added it as a planned feature for the next version, but I unfortunately still don't have a definite timeline for the 3.0 release. You may have some luck using anonymous dashboard access (see [here](https://community.atlassian.com/t5/Jira-questions/Anonymous-users-access-to-dashboards/qaq-p/92610)).

**Comment by metalcoat** [comment]
@superhawk610 I had trouble finding the switches initially myself, so I'll put in what I can.

**Comment by mike-bond** [comment]
@superhawk610 very useful information, I couldn't get it to work initially for JIRA, but I will keep looking

@metalcoat I think Google Slides will work, since it works in the preview, but I will have to test it with an actual chromecast.
